# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- master

pool: 'TestAgentPool'
  #vmImage: 

steps:
- task: TerraformCLI@0
  displayName: Terraform init
  inputs:
    command: 'init'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  displayName: Terraform plan
  inputs:
    command: 'plan'
    allowTelemetryCollection: false

- task: TerraformCLI@0
  displayName: Terraform apply
  inputs:
    command: 'apply'
    allowTelemetryCollection: false